version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "sigs.k8s.io/controller-runtime"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "k8s.io/client-go"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "k8s.io/apimachinery"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
