# permissions for end users to view clusterrelocations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusterrelocation-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-relocation-operator
    app.kubernetes.io/part-of: cluster-relocation-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterrelocation-viewer-role
rules:
- apiGroups:
  - rhsyseng.github.io
  resources:
  - clusterrelocations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rhsyseng.github.io
  resources:
  - clusterrelocations/status
  verbs:
  - get
