---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - update
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - apiservers
  verbs:
  - get
  - patch
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  verbs:
  - get
- apiGroups:
  - config.openshift.io
  resources:
  - imagedigestmirrorsets
  verbs:
  - create
  - delete
  - get
  - update
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - images
  verbs:
  - get
  - patch
- apiGroups:
  - config.openshift.io
  resources:
  - ingresses
  verbs:
  - get
  - patch
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - machineconfigs
  verbs:
  - create
  - delete
  - get
  - update
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - imagecontentsourcepolicies
  verbs:
  - create
  - delete
  - get
  - update
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - ingresscontrollers
  verbs:
  - get
  - patch
- apiGroups:
  - operators.coreos.com
  resources:
  - catalogsources
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - rhsyseng.github.io
  resources:
  - clusterrelocations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rhsyseng.github.io
  resources:
  - clusterrelocations/finalizers
  verbs:
  - update
- apiGroups:
  - rhsyseng.github.io
  resources:
  - clusterrelocations/status
  verbs:
  - get
  - patch
  - update
