apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: "[]"
    capabilities: "Full Lifecycle"
    categories: "Integration & Delivery"
    operators.openshift.io/infrastructure-features: '["disconnected"]'
  name: cluster-relocation-operator.v0.0.0
  namespace: placeholder
  support: RHsyseng
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: ClusterRelocation is the Schema for the clusterrelocations API
        displayName: Cluster Relocation
        kind: ClusterRelocation
        name: clusterrelocations.rhsyseng.github.io
        version: v1beta1
  description: Reconfigures a cluster after it has been moved to a new location
  displayName: Cluster Relocation Operator
  icon: []
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
    - supported: false
      type: OwnNamespace
    - supported: false
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - relocation
  links:
    - name: Cluster Relocation Operator
      url: https://rhsyseng.github.io
  maintainers:
    - email: lmcnaugh@redhat.com
      name: Logan McNaughton
    - email: dchavero@redhat.com
      name: Daniel Chavero
  maturity: beta
  minKubeVersion: 1.25.0
  provider:
    name: RHsyseng
  version: 0.0.0
