apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: cluster-relocation-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ClusterRelocation is the Schema for the clusterrelocations API
      displayName: Cluster Relocation
      kind: ClusterRelocation
      name: clusterrelocations.rhsyseng.github.io
      version: v1beta1
  description: Reconfigures a cluster after it has been moved to a new location
  displayName: Cluster Relocation Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - relocation
  links:
  - name: Cluster Relocation Operator
    url: https://cluster-relocation-operator.domain
  maturity: alpha
  provider:
    name: Cluster Relocation Operator
  version: 0.0.0
