apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: "[]"
    capabilities: Basic Install
    operators.openshift.io/infrastructure-features: '["disconnected"]'
    repository: https://github.com/RHsyseng/cluster-relocation-operator
  name: cluster-relocation-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: ClusterRelocation is the Schema for the clusterrelocations API
        displayName: Cluster Relocation
        kind: ClusterRelocation
        name: clusterrelocations.rhsyseng.github.io
        version: v1beta1
  description: Reconfigures a cluster after it has been moved to a new location
  displayName: Cluster Relocation Operator
  icon: []
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
    - supported: false
      type: OwnNamespace
    - supported: false
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - relocation
  links:
    - name: Cluster Relocation Operator
      url: https://rhsyseng.github.io
  maturity: alpha
  minKubeVersion: 1.25.0
  provider:
    name: Cluster Relocation Operator
  version: 0.0.0
