name: lint operator

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  lint-operator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=10m
